site_name: e-Título

repo_url: https://github.com/Requisitos-de-Software/2020.2-e-Titulo
repo_name: 'e-Título'

theme:
  name: material
  language: 'pt'
  logo: 'assets/icons/eTitulo.png'
  favicon: 'assets/icons/codercat.png'
  # features:
  #   - navigation.tabs

extra_css:
  - stylesheets/extra.css

nav:
  - Sobre: index.md
  - Planejamento: planejamento.md
  - Pré-rastreabilidade:
      - RichPictures: pre_rastreabilidade/rich_pictures.md
  - Elicitação de requisitos:
      - Personas: elicitacao/personas.md
      - Técnicas:
          - Brainstorming: elicitacao/tecnicas/brainstorming.md
          - Introspecção: elicitacao/tecnicas/introspeccao.md
          - Questionário: elicitacao/tecnicas/questionario.md
      - Requisitos elicitados: elicitacao/requisitos.md
  - Priorização de requisitos:
      - MoSCoW: priorizacao/moscow.md
      - Valor, Custo e Risco: priorizacao/valor_custo_risco.md
  - Apresentações:
      - Apresentação 1: apresentacoes/apresentacao1.md
      - Apresentação 2: apresentacoes/apresentacao2.md
  - Atas:
      - 03/03/2021: atas/reuniao_03_03.md
      - 10/03/2021: atas/reuniao_03_10.md
      - 17/03/2021: atas/reuniao_03_17.md